# Generated by Django 6.0.6 on 2026-06-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='correo',
            new_name='contra',
        ),
    ]
