# Generated by Django 6.0.6 on 2026-06-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_correo_student_contra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contra',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
