# Generated by Django 6.0.6 on 2026-06-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_contra_alter_student_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contra',
            field=models.CharField(),
        ),
    ]
