# Generated by Django 6.0.6 on 2026-06-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_contra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='creado',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='nombre',
            field=models.CharField(),
        ),
    ]
