# Generated by Django 6.0.6 on 2026-06-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_creado_alter_student_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
