# Generated by Django 6.0.6 on 2026-07-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contra',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
